# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [14]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Pets": [None, None, "", "", None]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score  Pets
0    Alice      25     2022-01-01  95.5  None
1      Bob  thirty     not a date  None  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022        None

### 🧯 2. Detecting Missing or Broken Values

In [15]:
df.isnull()

    Name    Age  Signup Date  Score   Pets
0  False  False        False  False   True
1  False  False        False   True   True
2  False  False        False  False  False
3  False   True         True  False  False
4   True  False        False  False   True

In [16]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
Pets           3
dtype: int64

In [18]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score  Pets
0  Alice      25     2022-01-01  95.5  None
1    Bob  thirty     not a date  None  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022        None

### 🧹 3. Cleaning Strategy Options

In [19]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score  Pets
0    Alice      25     2022-01-01  95.5  None
1      Bob  thirty     not a date   0.0  None
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022        None

In [20]:
df.dropna()

      Name Age Signup Date Score Pets
2  Charlie  35  2022/03/01  88.0

### 🧬 4. Data Type Fixes

In [21]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
Pets           object
dtype: object

In [22]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Pets                   object
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [31]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipython-input-1713118361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipython-input-1713118361.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)

In [30]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipython-input-3000949103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [29]:
df["Name"].fillna("Unknown", inplace=True)
df["Pets"].fillna("Unknows", inplace=True)

### 🤓 6. Cleaned Data Review

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
 4   Pets         5 non-null      object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 332.0+ bytes

In [33]:
df.describe(include="all")

         Name        Age          Signup Date     Score     Pets
count       5   5.000000                    5   5.00000        5
unique      5        NaN                  NaN       NaN        2
top     Alice        NaN                  NaN       NaN  Unknows
freq        1        NaN                  NaN       NaN        3
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000      NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.00000      NaN
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000      NaN
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000      NaN
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000      NaN
max       NaN  40.000000  2022-01-01 00:00:00  95.50000      NaN
std       NaN   5.477226                  NaN   2.66927      NaN

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [39]:
csvData = pd.read_csv("sample_data/pokemon.csv")
csvData.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [48]:
csvData["Type 2"].fillna("Nothing", inplace=True)

/tmp/ipython-input-187047240.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csvData["Type 2"].fillna("Nothing", inplace=True)

In [49]:
csvData.dropna()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,Nothing,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [51]:
csvData.isnull().sum()

#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [52]:
csvData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      800 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [54]:
csvData.describe(include="all")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
count,800.000000,800,800,800,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000,800
unique,NaN,800,18,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,PumpkabooSuper Size,Water,Nothing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,NaN,1,112,386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735
mean,362.813750,NaN,NaN,NaN,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375,NaN
std,208.343798,NaN,NaN,NaN,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129,NaN
min,1.000000,NaN,NaN,NaN,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000,NaN
25%,184.750000,NaN,NaN,NaN,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000,NaN
50%,364.500000,NaN,NaN,NaN,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000,NaN
75%,539.250000,NaN,NaN,NaN,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000,NaN
max,721.000000,NaN,NaN,NaN,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000,NaN

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |