# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## 🔹 LEARNING GOALS:
- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

### 📥 1. Load the Dataset

In [15]:
import pandas as pd
df = pd.read_csv("sample_data/students.csv")
df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 🔎 2. Inspect and Audit the Data

In [16]:
# Basic overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     50 non-null     object
 1   last_name      50 non-null     object
 2   math_score     50 non-null     int64
 3   science_score  50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB

In [17]:
# Summary stats
df.describe()

       math_score  science_score
count    50.00000      50.000000
mean     77.56000      80.240000
std      12.17753      11.659384
min      60.00000      62.000000
25%      66.25000      73.000000
50%      75.50000      78.000000
75%      87.00000      89.000000
max     100.00000     100.000000

### 🧼 3. Clean Missing or Invalid Data

In [18]:
# Check for missing values
df.isnull().sum()

first_name       0
last_name        0
math_score       0
science_score    0
dtype: int64

In [20]:
# Drop rows with missing names
df.dropna(subset=["first_name", "last_name"], inplace=True)

# Fill any missing scores with column average
df["math_score"].fillna(df["math_score"].mean(), inplace=True)
df["science_score"].fillna(df["science_score"].mean(), inplace=True)

/tmp/ipython-input-210016614.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["math_score"].fillna(df["math_score"].mean(), inplace=True)
/tmp/ipython-input-210016614.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["science_score"].fillna(df["science_score"].mean(), inplace=True)

### 🧠 4. Feature Engineering (New Columns)

In [21]:
# Add average and grade
df["average_score"] = (df["math_score"] + df["science_score"]) / 2

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood         100             95           97.5     A
1      Angel     Clark          67             78           72.5     C
2     Joshua     Adams          61            100           80.5     B
3    Jeffrey    Zuniga          77             99           88.0     B
4       Jill      Wong          75             83           79.0     C

### 🔽 5. Sorting and Filtering

In [22]:
# Top performers
df[df["average_score"] > 90].sort_values(by="average_score", ascending=False).head()

     first_name last_name  math_score  science_score  average_score grade
26  Christopher     Rocha          97            100           98.5     A
0      Danielle      Wood         100             95           97.5     A
17      Bridget   Johnson          92            100           96.0     A
46        Craig   Ferrell          94             96           95.0     A
25      Matthew    Foster          88             98           93.0     A

### 📊 6. Group and Describe by Grade

In [23]:
# How many of each grade?
df["grade"].value_counts()

grade
C    22
B    14
A     7
D     7
Name: count, dtype: int64

In [24]:
# Average scores per grade group
df.groupby("grade")[["math_score", "science_score", "average_score"]].mean()

       math_score  science_score  average_score
grade
A       95.285714      93.857143      94.571429
B       81.500000      86.857143      84.178571
C       73.590909      75.590909      74.590909
D       64.428571      68.000000      66.214286

### 💾 7. Save the Cleaned Dataset

In [25]:
df.to_csv("student_scores_cleaned.csv", index=False)

### 🧠 Challenge Task

> Your turn! Filter out students who got a D, sort by last name, and export to a new file:
- Only include columns: `first_name`, `last_name`, `grade`
- Save it as `"d_students.csv"`

In [26]:
df.drop(df[df["grade"] == "D"].index, inplace=True)
df

     first_name  last_name  math_score  science_score  average_score grade
0      Danielle       Wood         100             95           97.5     A
1         Angel      Clark          67             78           72.5     C
2        Joshua      Adams          61            100           80.5     B
3       Jeffrey     Zuniga          77             99           88.0     B
4          Jill       Wong          75             83           79.0     C
5         Erica      Lynch          74             96           85.0     B
6      Patricia    Jackson          68             72           70.0     C
8        Robert     Martin          94             62           78.0     C
10      Jeffery       Mayo          97             78           87.5     B
11      William     Bowman          87             65           76.0     C
14        Debra    Cameron          65             84           74.5     C
15          Amy    Parsons          73             77           75.0     C
16      Jeffrey      Perez          74             89           81.5     B
17      Bridget    Johnson          92            100           96.0     A
18         Lisa    Stewart          98             83           90.5     A
20        Linda      Clark          95             83           89.0     B
21        Helen       Hahn          72             82           77.0     C
22      Matthew     Walter          94             73           83.5     B
23         Eric    Edwards          86             77           81.5     B
25      Matthew     Foster          88             98           93.0     A
26  Christopher      Rocha          97            100           98.5     A
27        Colin      Ellis          77             70           73.5     C
28      Melanie      Baker          60             94           77.0     C
29    Cassandra     Wright          70             75           72.5     C
30      Lindsay    Hoffman          87             70           78.5     C
31      Jessica      Baker          81             89           85.0     B
32       Amanda   Richards          77             84           80.5     B
33       Teresa      Hurst          69             77           73.0     C
34     Nicholas       Ross          73            100           86.5     B
35       Andrea   Robinson          81             95           88.0     B
36        Maria     Bright          66             74           70.0     C
37    Christine      Hicks          65             80           72.5     C
38     Michelle      Davis          84             63           73.5     C
39      Barbara   Williams          66             74           70.0     C
40        Janet  Rodriguez          82             62           72.0     C
41      Brandon     Burton          82             80           81.0     B
42       Jeremy     Conner          98             85           91.5     A
43        Keith  Henderson          76             77           76.5     C
45        Jesse      James          89             73           81.0     B
46        Craig    Ferrell          94             96           95.0     A
47       Joshua       Rice          67             80           73.5     C
48      Cynthia     Maddox          84             73           78.5     C
49      Michael   Valencia          65             91           78.0     C

In [27]:
df.drop(["math_score", "science_score", "average_score"], axis=1, inplace=True)
df

     first_name  last_name grade
0      Danielle       Wood     A
1         Angel      Clark     C
2        Joshua      Adams     B
3       Jeffrey     Zuniga     B
4          Jill       Wong     C
5         Erica      Lynch     B
6      Patricia    Jackson     C
8        Robert     Martin     C
10      Jeffery       Mayo     B
11      William     Bowman     C
14        Debra    Cameron     C
15          Amy    Parsons     C
16      Jeffrey      Perez     B
17      Bridget    Johnson     A
18         Lisa    Stewart     A
20        Linda      Clark     B
21        Helen       Hahn     C
22      Matthew     Walter     B
23         Eric    Edwards     B
25      Matthew     Foster     A
26  Christopher      Rocha     A
27        Colin      Ellis     C
28      Melanie      Baker     C
29    Cassandra     Wright     C
30      Lindsay    Hoffman     C
31      Jessica      Baker     B
32       Amanda   Richards     B
33       Teresa      Hurst     C
34     Nicholas       Ross     B
35       Andrea   Robinson     B
36        Maria     Bright     C
37    Christine      Hicks     C
38     Michelle      Davis     C
39      Barbara   Williams     C
40        Janet  Rodriguez     C
41      Brandon     Burton     B
42       Jeremy     Conner     A
43        Keith  Henderson     C
45        Jesse      James     B
46        Craig    Ferrell     A
47       Joshua       Rice     C
48      Cynthia     Maddox     C
49      Michael   Valencia     C

In [28]:
df.to_csv("d_students.csv", index=False)

### 📝 Summary

This lab gave you hands-on experience with:
- Cleaning nulls and type mismatches
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is now ready for real-world messiness. 🧹🛠️