# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [1]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [4]:
import pandas as pd

data = """
       Name,Age,Letter Grade
       Pedro, 24, C
       Alex, 21, A
       Ana, 22, B
       """
with open("grades.csv", "w") as f:
  f.write(data)

dataFrame = pd.read_csv("grades.csv")
dataFrame

           Name  Age Letter Grade
0         Pedro   24            C
1          Alex   21            A
2           Ana   22            B

## 2. Exploring DataFrames

In [5]:
# Look at the first rows
df.head()

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [6]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [7]:
# Summary statistics
df.describe()

             Age  Score
count   3.000000    3.0
mean   23.333333   90.0
std     1.527525    5.0
min    22.000000   85.0
25%    22.500000   87.5
50%    23.000000   90.0
75%    24.000000   92.5
max    25.000000   95.0

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [9]:
dataFrame.head()

           Name  Age Letter Grade
0         Pedro   24            C
1          Alex   21            A
2           Ana   22            B

In [10]:
dataFrame.describe()

             Age
count   3.000000
mean   22.333333
std     1.527525
min    21.000000
25%    21.500000
50%    22.000000
75%    23.000000
max    24.000000

## 3. Writing CSV Files

In [ ]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [13]:
dataFrame.to_csv("my_data.csv", index=False)

## 4. Reading Excel Files

In [ ]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [14]:
dataFrame.to_excel("grades.xlsx", index=False)
pd.read_excel("grades.xlsx")

           Name  Age Letter Grade
0         Pedro   24            C
1          Alex   21            A
2           Ana   22            B

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.